### ISSUE TITLE
make it more open

### ISSUE THREAD

**Issue by vnitinv** [Juniper/OpenClos#103]
"For general questions and support, send e-mail to openclos-support@juniper.net."
Its better to have something like google group, where people can discuss topics. Being on group gives feasibility to search for questions and respective answer in future too. 
check this out (which we use)

https://groups.google.com/forum/#!forum/junos-python-ez

**Comment by unalix** [comment]
I tried sending e-mail to  openclos-support@juniper.net and got this:

openclos-eng@juniper.net
Your message can't be delivered because delivery to this address is restricted to authenticated Sender.
For more information about this issue, see DSN code 5.7.1 in Exchange Online - Office 365.

**Comment by barnesry** [comment]
To close off this request there is a Google Group available here. 
https://groups.google.com/forum/#!forum/openclos

vglinskiy : I've forwarded your note to the folks on that distro who should be able to resolve.
